
package org.um.vendorwsdl;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VendorManagerWebService", targetNamespace = "http://um.org/vendorwsdl", wsdlLocation = "http://localhost:8080/vendor-manager-1.0-SNAPSHOT/webservices/VendorManagerImpl?wsdl")
public class VendorManagerWebService
    extends Service
{

    private final static URL VENDORMANAGERWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.um.vendorwsdl.VendorManagerWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.um.vendorwsdl.VendorManagerWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/vendor-manager-1.0-SNAPSHOT/webservices/VendorManagerImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/vendor-manager-1.0-SNAPSHOT/webservices/VendorManagerImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VENDORMANAGERWEBSERVICE_WSDL_LOCATION = url;
    }

    public VendorManagerWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VendorManagerWebService() {
        super(VENDORMANAGERWEBSERVICE_WSDL_LOCATION, new QName("http://um.org/vendorwsdl", "VendorManagerWebService"));
    }

    /**
     * 
     * @return
     *     returns VendorManagerImpl
     */
    @WebEndpoint(name = "VendorManagerPort")
    public VendorManagerImpl getVendorManagerPort() {
        return super.getPort(new QName("http://um.org/vendorwsdl", "VendorManagerPort"), VendorManagerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VendorManagerImpl
     */
    @WebEndpoint(name = "VendorManagerPort")
    public VendorManagerImpl getVendorManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://um.org/vendorwsdl", "VendorManagerPort"), VendorManagerImpl.class, features);
    }

}
