
package org.um.userwsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "InvalidUserException", targetNamespace = "http://um.org/userwsdl")
public class InvalidUserException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidUserException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidUserException_Exception(String message, InvalidUserException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidUserException_Exception(String message, InvalidUserException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.org.um.userwsdl.InvalidUserException
     */
    public InvalidUserException getFaultInfo() {
        return faultInfo;
    }

}
